
export function getConstructionPool() {

    const constructionPool = [
        "Allen M. Sumner",
        "Avrora",
        "Bristol",
        "Charybdis",
        "Dido",
        "Dido µ",
        "Kawakaze",
        "Kazagumo",
        "Montpelier",
        "Noshiro",
        "San Diego",
        "Swiftsure",
        "Tashkent µ",
        "Yukikaze",
        "Akashi",
        "Belfast",
        "Ingraham",
        "Reno",
        "Aurora",
        "Biloxi",
        "Birmingham",
        "Black Prince",
        "Chang Chun",
        "Chao Ho",
        "Cleveland",
        "Cleveland µ",
        "Denver",
        "Fubuki",
        "Gloucester",
        "Hanazuki",
        "Javelin",
        "Kasumi",
        "Laffey",
        "Lena",
        "Little Bel",
        "Mikuma",
        "Mogami",
        "Mullany",
        "Naganami",
        "Penelope",
        "Shirayuki",
        "St. Louis",
        "Stephen Potter",
        "Tai Yuan",
        "Vincenzo Gioberti",
        "Yat Sen",
        "Ying Swei",
        "Ayanami",
        "Cooper",
        "Hardy",
        "Maury",
        "Yuubari",
        "Z2",
        "Z23",
        "Acasta",
        "Achilles",
        "Ajax",
        "Amazon",
        "Ardent",
        "Asashio",
        "Atlanta",
        "Bache",
        "Brooklyn",
        "Concord",
        "Curacoa",
        "Curlew",
        "Fletcher",
        "Forbin",
        "Fumizuki",
        "Glasgow",
        "Halsey Powell",
        "Hamakaze",
        "Hammann",
        "Hatakaze",
        "Hatsuharu",
        "Hobby",
        "Isokaze",
        "Jersey",
        "Juneau",
        "Jupiter",
        "Kalk",
        "Kamikaze",
        "Kimberly",
        "Kiyonami",
        "Le Mars",
        "Matsukaze",
        "Naka",
        "Ooshio",
        "Phoenix",
        "Smalley",
        "Southampton",
        "Stanly",
        "Tanikaze",
        "Urakaze",
        "Wakaba",
        "Yuugure",
        "Z19",
        "Leipzig",
        "Marblehead",
        "Aulick",
        "Beagle",
        "Bulldog",
        "Cassin",
        "Comet",
        "Craven",
        "Crescent",
        "Cygnet",
        "Downes",
        "Foote",
        "Foxhound",
        "Koln",
        "Konigsberg",
        "Karlsruhe",
        "Kisaragi",
        "Leander",
        "McCall",
        "Mutsuki",
        "Nagara",
        "Omaha",
        "Raleigh",
        "Spence",
        "Uzuki",
        "Alabama",
        "Amagi",
        "Baltimore",
        "Bismarck",
        "Gascogne µ",
        "Hood",
        "Jean Bart",
        "Kaga (Battleship)",
        "King George V",
        "Littorio",
        "Massachusetts",
        "Nagato",
        "Pola",
        "Prinz Eugen",
        "Suruga",
        "Takao",
        "Tosa",
        "Warspite",
        "Zara",
        "Bremerton",
        "Abercrombie",
        "Admiral Hipper µ",
        "Arizona",
        "Ashigara",
        "Baltimore µ",
        "Deutschland",
        "Dunkerque",
        "Erebus",
        "Giulio Cesare",
        "Hiei",
        "Hiei-chan",
        "Houston",
        "Indianapolis",
        "Kirishima",
        "London",
        "Nelson",
        "Queen Elizabeth",
        "Renown",
        "Suzuya",
        "Terror",
        "York",
        "Dorsetshire",
        "Exeter",
        "Rodney",
        "Wichita",
        "Ajax",
        "Atlanta",
        "California",
        "Chicago",
        "Ise",
        "Kent",
        "Norfolk",
        "Northampton",
        "Pennsylvania",
        "Phoenix",
        "Portland",
        "Repulse",
        "Shropshire",
        "Suffolk",
        "Sussex",
        "Tennessee",
        "Hyuuga",
        "Leipzig",
        "Aoba",
        "Koln",
        "Konigsberg",
        "Karlsruhe",
        "Kinugasa",
        "Leander",
        "Nevada",
        "Oklahoma",
        "Omaha",
        "Pensacola",
        "Raleigh",
        "Akagi µ",
        "Centaur",
        "Enterprise",
        "Essex",
        "Formidable",
        "I-13",
        "I-168",
        "I-19",
        "Ryuuhou",
        "Shangri-La",
        "Taihou µ",
        "U-101",
        "U-47",
        "U-81",
        "U-96",
        "Victorious",
        "Akashi",
        "Graf Zeppelin",
        "Illustrious",
        "Intrepid",
        "Taihou",
        "Akagi-chan",
        "Albacore µ",
        "Chaser",
        "Chen Hai",
        "Glorious",
        "Hornet",
        "Houston",
        "I-25",
        "I-26",
        "I-56",
        "I-58",
        "Indianapolis",
        "Lexington",
        "London",
        "Saratoga",
        "Surcouf",
        "U-110",
        "U-522",
        "U-556",
        "U-73",
        "Unicorn",
        "Vestal",
        "Yorktown",
        "Zeppy",
        "Ark Royal",
        "Dorsetshire",
        "Nautilus",
        "Wichita",
        "Ajax",
        "Atlanta",
        "Chicago",
        "Kent",
        "Long Island",
        "Norfolk",
        "Northampton",
        "Phoenix",
        "Portland",
        "Shropshire",
        "Suffolk",
        "Leipzig",
        "Aoba",
        "Bogue",
        "Hermes",
        "Koln",
        "Konigsberg",
        "Karlsruhe",
        "Kinugasa",
        "Langley",
        "Leander",
        "Omaha",
        "Pensacola",
        "Raleigh",
        "Ranger",
    ]

    return constructionPool
}

