

export function getUltraRareShips() {

    const UltraRare = [
        "Specialized Bulin Custom MKIII",
        "New Jersey",
        "Vanguard",
        "Musashi",
        "Shinano",
        "Shimakaze",
        "Ulrich von Hutten",
        "Kronshtadt",
        "Yorktown II",
        "Friedrich der Grobe",
        "Plymouth",
        "Brest",
        "Azuma",
        "Drake",
        "Hakuryuu",
        "Agir",
    ]

    return UltraRare
}


export function getSuperRareShips() {

    const SuperRare = [
        "Prototype Bulin MKII",
        "Eldridge",
        "San Diego",
        "Baltimore",
        "North Carolina",
        "Washington",
        "South Dakota",
        "Enterprise",
        "Dido",
        "Belfast",
        "Hood",
        "Warspite",
        "King George V",
        "Prince of Wales",
        "Duke of York",
        "Illustrious",
        "Victorious",
        "Formidable",
        "Yuudachi",
        "Yukikaze",
        "Chikuma",
        "Takao",
        "Atago",
        "Maya",
        "Choukai",
        "Nagato",
        "Kii",
        "Tosa",
        "Akagi",
        "Kaga",
        "Shoukaku",
        "Zuikaku",
        "Taihou",
        "Akashi",
        "Blucher",
        "Prinz Eugen",
        "Bismarck",
        "Tirpitz",
        "Graf Zeppelin",
        "Avrora",
        "Z46",
        "Kawakaze",
        "Mikasa",
        "Noshiro",
        "Sakawa",
        "Montpelier",
        "I-19",
        "U-81",
        "U-47",
        "Le Triomphant",
        "Jean Bart",
        "Massachusetts",
        "Centaur",
        "Essex",
        "Albacore",
        "Minneapolis",
        "Amagi",
        "Kaga (Battleship)",
        "Sirius",
        "Shangri-La",
        "Bunker Hill",
        "I-13",
        "Swiftsure",
        "Le Malin",
        "I-168",
        "U-101",
        "Alabama",
        "Cavalla",
        "Littorio",
        "Zara",
        "Gascogne µ",
        "Akagi µ",
        "Suruga",
        "Ryuuhou",
        "Tashkent",
        "Kirov",
        "Chapayev",
        "Sovetskaya Belorussiya",
        "Sovetskaya Rossiya",
        "Intrepid",
        "Bremerton",
        "Reno",
        "Richelieu",
        "Jeanne d'Arc",
        "Algerie",
        "Howe",
        "Perseus",
        "Hermione",
        "U-96",
        "Suzutsuki",
        "Taihou µ",
        "Tashkent µ",
        "Dido µ",
        "Roon µ",
        "Illustrious µ",
        "Le Malin µ",
        "Peter Strasser",
        "Prinz Heinrich",
        "U-37",
        "Pola",
        "Tallinn",
        "Vittorio Veneto",
        "Duca degli Abruzzi",
        "Aquila",
        "Allen M. Sumner",
        "Ticonderoga",
        "San Francisco",
        "Archerfish",
        "Kazagumo",
        "Ingraham",
        "Katsuragi",
        "New Orleans",
        "Le Terrible",
        "Magdeburg",
        "Prinz Adalbert",
        "Charybdis",
        "Bristol",
        "Kiev",
        "Volga",
        "Impero",
        "Pompeo Magno",
        "Seydlitz",
        "Lutzow",
        "Emden",
        "Jervis",
        "Indomitable",
        "Joffre",
        "L'Indomptable",
        "Leonardo da Vinci",
        "Giuseppe Garibaldi",
        "Roma",
        "Brunhilde",
        "Wakatsuki",
        "Janus",
        "Albion",
        "Royal Fortune",
        "Hornet II",
        "Northampton II",
        "Kuybyshev",
        "Theseus",
        "Prinz Rupprecht",
        "Harbin",
        "Chkalov",
        "Neptune",
        "Monarch",
        "Ibuki",
        "Izumo",
        "Roon",
        "Saint Louis",
        "Seattle",
        "Georgia",
        "Kitakaze",
        "Gascogne",
        "Cheshire",
        "Mainz",
        "Odin",
        "Champagne",
        "Anchorage",
        "August von Parseval",
        "Marco Polo",
        "Hiryuu META",
        "Ark Royal META",
        "Helena META",
        "Souryuu META",
        "Gneisenau META",
        "Scharnhorst META",
        "Repulse META",
        "Renown META",
        "Arizona META",
        "Marie Rose",
        "Honoka",
        "Kasumi (Venus Vacation)",
        "Misaki",
        "Haruka Amami",
        "Chihaya Kisaragi",
        "Iori Minase",
        "Azusa Miura",
        "Rikka Takarada",
        "Akane Shinjo",
        "Yume Minami",
        "Chise Asukagawa",
        "Reisalin Stout",
        "Klaudia Valentz",
        "Patricia Abelheim",
        "Kala Ideas",
        "Purple Heart",
        "Black Heart",
        "White Heart",
        "Green Heart",
        "Kuon",
        "Nekone",
        "Rurutie",
        "Elegant Kizuna AI",
        "Anniversary Kizuna AI",
        "Super Gamer Kizuna AI",
        "Shirakami Fubuki",
        "Tokino Sora",
        "Minato Aqua",
    ]

    return SuperRare
}

export function getEliteShips() {

    const Elite = [
        "Universal Bulin",
        "Maury",
        "Charles Ausburne",
        "Laffey",
        "Helena",
        "Cleveland",
        "Columbia",
        "Houston",
        "Indianapolis",
        "Astoria",
        "Quincy",
        "Vincennes",
        "Wichita",
        "Arizona",
        "Colorado",
        "Maryland",
        "West Virginia",
        "Lexington",
        "Saratoga",
        "Yorktown",
        "Hornet",
        "Vestal",
        "Grenville",
        "Glowworm",
        "Hardy",
        "Javelin",
        "Vampire",
        "Sheffield",
        "Manchester",
        "Gloucester",
        "Edinburgh",
        "Aurora",
        "London",
        "Dorsetshire",
        "York",
        "Exeter",
        "Renown",
        "Queen Elizabeth",
        "Nelson",
        "Rodney",
        "Unicorn",
        "Eagle",
        "Ark Royal",
        "Glorious",
        "Erebus",
        "Terror",
        "Fubuki",
        "Shirayuki",
        "Miyuki",
        "Ayanami",
        "Hibiki",
        "Shigure",
        "Nowaki",
        "Yuubari",
        "Yura",
        "Kinu",
        "Mogami",
        "Mikuma",
        "Ashigara",
        "Haguro",
        "Kongou",
        "Hiei",
        "Haruna",
        "Kirishima",
        "Mutsu",
        "Houshou",
        "Ryuujou",
        "Souryuu",
        "Hiryuu",
        "Z1",
        "Z23",
        "Z25",
        "Admiral Hipper",
        "Deutschland",
        "Admiral Graf Spee",
        "Scharnhorst",
        "Gneisenau",
        "An Shan",
        "Fu Shun",
        "Chang Chun",
        "Tai Yuan",
        "Yat Sen",
        "Ning Hai",
        "Ping Hai",
        "Umikaze",
        "Yamakaze",
        "Niizuki",
        "Harutsuki",
        "Yoizuki",
        "Nicholas",
        "St. Louis",
        "Jintsuu",
        "Agano",
        "Matchless",
        "Musketeer",
        "Denver",
        "Little Bel",
        "Abercrombie",
        "I-26",
        "I-58",
        "Dace",
        "U-557",
        "Z35",
        "Emile Bertin",
        "Surcouf",
        "Dunkerque",
        "Le Temeraire",
        "Makinami",
        "Mullany",
        "Chaser",
        "Independence",
        "Z2",
        "Suzuya",
        "Hiei-chan",
        "Akagi-chan",
        "Zeppy",
        "U-556",
        "U-73",
        "Z36",
        "Lena",
        "Clevelad",
        "Li'l Sandy",
        "L'Opiniâtre",
        "I-25",
        "I-56",
        "U-522",
        "Bataan",
        "Birmingham",
        "Black Prince",
        "Giulio Cesare",
        "Carabiniere",
        "U-110",
        "Cleveland µ",
        "Sheffield µ",
        "Admiral Hipper µ",
        "Kasumi",
        "Biloxi",
        "Uranami",
        "Grozny",
        "Minsk",
        "Pamiat Merkuria",
        "Gangut",
        "Cooper",
        "Bluegill",
        "Hanazuki",
        "Naganami",
        "Little Renown",
        "Tartu",
        "La Galissonniere",
        "Vauquelin",
        "Bearn",
        "Little Illustrious",
        "Eskimo",
        "Valiant",
        "Icarus",
        "Z26",
        "Kumano",
        "Chitose",
        "Chiyoda",
        "Kashino",
        "Princeton",
        "Albacore µ",
        "Baltimore µ",
        "Weser",
        "Nurnberg",
        "Z24",
        "Z28",
        "Vincenzo Gioberti",
        "Stremitelny",
        "U-410",
        "Ying Swei",
        "Chao Ho",
        "Penelope",
        "Gremyashchy",
        "Murmansk",
        "Gromky",
        "Torricelli",
        "Maestrale",
        "Libeccio",
        "Nicoloso da Recco",
        "Stephen Potter",
        "Amagi-chan",
        "Boise",
        "Morrison",
        "Little Enterprise",
        "Nautilus",
        "Maille Breze",
        "Foch",
        "Elbe",
        "U-1206",
        "Hai Tien",
        "Hai Chi",
        "Chen Hai",
        "Arkhangelsk",
        "Soobrazitelny",
        "Trieste",
        "Thuringen",
        "Yorck",
        "Elbing",
        "Little Prinz Eugen",
        "Bellona",
        "Little Cheshire",
        "Revenge",
        "Enterprise (Royal Navy)",
        "Bolzano",
        "Alfredo Oriani",
        "Emanuele Pessagno",
        "Z16",
        "Little Spee",
        "Langley II",
        "Hammann II",
        "Hwah Jah",
        "Ting An",
        "Fusou META",
        "Hiyou META",
        "Junyou META",
        "Yamashiro META",
        "Memphis META",
        "Trento META",
        "Hunter META",
        "Fortune META",
        "Sheffield META",
        "Nagisa",
        "Nyotengu",
        "Monica",
        "Ritsuko Akizuki",
        "Ami Futami",
        "Mami Futami",
        "Hass",
        "Namiko",
        "Mujina",
        "Lila Decyrus",
        "Serri Glaus",
        "Neptune (Neptunia)",
        "Noire",
        "Blanc",
        "Vert",
        "22",
        "33",
        "Uruuru",
        "Saraana",
        "Fumiruiru",
        "Kizuna AI",
        "Natsuiro Matsuri",
        "Nakiri Ayame",
        "Murasaki Shion",
        "Ookami Mio",
    ]

    return Elite
}

export function getRareShips() {

    const Rare = [
        "Dewey",
        "Gridley",
        "Fletcher",
        "Thatcher",
        "Benson",
        "Sims",
        "Hammann",
        "Brooklyn",
        "Phoenix",
        "Atlanta",
        "Juneau",
        "Northampton",
        "Chicago",
        "Portland",
        "Pennsylvania",
        "Tennessee",
        "California",
        "Long Island",
        "Wasp",
        "Amazon",
        "Acasta",
        "Ardent",
        "Fortune",
        "Hunter",
        "Juno",
        "Achilles",
        "Ajax",
        "Southampton",
        "Arethusa",
        "Galatea",
        "Shropshire",
        "Kent",
        "Suffolk",
        "Norfolk",
        "Repulse",
        "Akatsuki",
        "Ikazuchi",
        "Inazuma",
        "Shiratsuyu",
        "Kagerou",
        "Hatsuharu",
        "Wakaba",
        "Hatsushimo",
        "Ariake",
        "Yuugure",
        "Kuroshio",
        "Oyashio",
        "Isuzu",
        "Myoukou",
        "Nachi",
        "Fusou",
        "Yamashiro",
        "Ise",
        "Hyuuga",
        "Hiyou",
        "Junyou",
        "Shouhou",
        "Leipzig",
        "Bailey",
        "Z19",
        "Kamikaze",
        "Matsukaze",
        "Fumizuki",
        "Nagatsuki",
        "Kiyonami",
        "Radford",
        "Jenkins",
        "Honolulu",
        "Jupiter",
        "Jersey",
        "Sendai",
        "Naka",
        "Urakaze",
        "Isokaze",
        "Hamakaze",
        "Tanikaze",
        "Fiji",
        "Jamaica",
        "Asashio",
        "Ooshio",
        "Michishio",
        "Arashio",
        "Sussex",
        "Z18",
        "Forbin",
        "Le Mars",
        "Bush",
        "Memphis",
        "Newcastle",
        "Hobby",
        "Kalk",
        "Hazelwood",
        "Concord",
        "Hatakaze",
        "Curacoa",
        "Curlew",
        "Kimberly",
        "Echo",
        "San Juan",
        "Aylwin",
        "Bache",
        "Stanly",
        "Conte di Cavour",
        "Trento",
        "Smalley",
        "Glasgow",
        "Halsey Powell",
        "Casablanca",
        "Marblehead",
        "Oite",
    ]

    return Rare
}

export function getNormalShips() {

    const Normal = [
        "Cassin",
        "Downes",
        "Craven",
        "McCall",
        "Aulick",
        "Foote",
        "Spence",
        "Omaha",
        "Raleigh",
        "Pensacola",
        "Salt Lake City",
        "Nevada",
        "Oklahoma",
        "Bogue",
        "Langley",
        "Ranger",
        "Beagle",
        "Bulldog",
        "Comet",
        "Crescent",
        "Cygnet",
        "Foxhound",
        "Leander",
        "Hermes",
        "Shiranui",
        "Nagara",
        "Abukuma",
        "Furutaka",
        "Kako",
        "Aoba",
        "Kinugasa",
        "Konigsberg",
        "Karlsruhe",
        "Koln",
        "Z20",
        "Z21",
        "Mutsuki",
        "Kisaragi",
        "Uzuki",
        "Minazuki",
        "Mikazuki",
        "Richmond",
    ]

    return Normal

}
