

export function getRequisitionShips(){

    const requisition = [
        "Enterprise",
        "Hood",
        "Illustrious",
        "Prinz Eugen",
        "San Diego",
        "Takao",
        "Warspite",
        "Atago",
        "Prince of Wales",
        "Belfast",
        "Z46",
        "Mikasa",
        "Tirpitz",
        "Le Malin",
        "Le Triomphant",
        "Minneapolis",
        "North Carolina",
        "Shoukaku",
        "Sirius",
        "Washington",
        "Zuikaku",
        "Charles Ausburne",
        "Helena",
        "Cleveland",
        "Houston",
        "Indianapolis",
        "Arizona",
        "Lexington",
        "Saratoga",
        "Yorktown",
        "Hornet",
        "Vestal",
        "Glowworm",
        "Vampire",
        "Edinburgh",
        "London",
        "York",
        "Exeter",
        "Renown",
        "Queen Elizabeth",
        "Nelson",
        "Rodney",
        "Unicorn",
        "Ark Royal",
        "Erebus",
        "Terror",
        "Nowaki",
        "Z1",
        "Admiral Hipper",
        "L'Opiniatre",
        "Z25",
        "Z35",
        "Harutsuki",
        "Matchless",
        "Sheffield",
        "U-557",
        "Yoizuki",
        "Gridley",
        "Fletcher",
        "Thatcher",
        "Sims",
        "Hammann",
        "Brooklyn",
        "Phoenix",
        "Atlanta",
        "Juneau",
        "Northampton",
        "Chicago",
        "Portland",
        "Pennsylvania",
        "Tennessee",
        "California",
        "Long Island",
        "Amazon",
        "Fortune",
        "Juno",
        "Achilles",
        "Ajax",
        "Arethusa",
        "Galatea",
        "Shropshire",
        "Kent",
        "Suffolk",
        "Norfolk",
        "Repulse",
        "Ise",
        "Hyuuga",
        "Jamaica",
        "Cassin",
        "Downes",
        "Craven",
        "McCall",
        "Aulick",
        "Foote",
        "Spence",
        "Omaha",
        "Raleigh",
        "Pensacola",
        "Nevada",
        "Oklahoma",
        "Bogue",
        "Langley",
        "Ranger",
        "Beagle",
        "Bulldog",
        "Comet",
        "Crescent",
        "Cygnet",
        "Foxhound",
        "Leander",
        "Hermes",
        "Konigsberg",
        "Karlsruhe",
        "Koln",
    ]

    return requisition
}


export function getMedalShopShips(){

    // medal shop offers a subset of requisition ships (the super rares)

    const medalShopShips = [
        "Enterprise",
        "Hood",
        "Illustrious",
        "Prinz Eugen",
        "San Diego",
        "Takao",
        "Warspite",
        "Atago",
        "Prince of Wales",
        "Belfast",
        "Z46",
        "Mikasa",
        "Tirpitz",
        "Le Malin",
        "Le Triomphant",
        "Minneapolis",
        "North Carolina",
        "Shoukaku",
        "Sirius",
        "Washington",
        "Zuikaku",
    ]

    return medalShopShips
}


